import './globals.css'
import { Providers } from "@/app/providers";
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + ' fixed h-screen w-screen'}>
        <Providers>
          { children }
        </Providers>
      </body>
    </html>
  )
}
